<%@ page language="C#" autoeventwireup="true" inherits="Home, App_Web_r0l5cs0s" masterpagefile="~/MasterPage/Home.master" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

  <asp:Content ID="Content1" Runat="Server" ContentPlaceHolderID="LocalScripts" >
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Tender generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Tender, WOW Slider, html slider, jquery photo gallery" />
	<meta name="description" content="Tender created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body>
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/tender1.jpg" alt="t1" title="Tender" id="wows1_0"/></li>
<li><img src="data1/images/tender2.jpg" alt="t2" title="Tender" id="wows1_1"/></li>
<li><img src="data1/images/tender3.jpg" alt="t3" title="Tender" id="wows1_2"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="t1"><img src="data1/tooltips/tender1.jpg" alt="t1"/>1</a>
<a href="#" title="t2"><img src="data1/tooltips/tender2.jpg" alt="t2"/>2</a>
<a href="#" title="t3"><img src="data1/tooltips/tender3.jpg" alt="t3"/>3</a>
</div></div>
<span class="wsl"><a href="http://wowslider.com">javascript slider</a> by WOWSlider.com v5.3</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>
</asp:Content>
<asp:Content ContentPlaceHolderID ="cphLogin" runat ="server" >

    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server">
    </asp:ToolkitScriptManager>

    <%-- <form id ="frm" runat ="server" >
    <asp:Login ID="AdminLogin" runat="server" UserNameLabelText="EmaillId:" 
        onauthenticate="AdminLogin_Authenticate" Width="100px">
    </asp:Login>
    </form>--%>

   <%-- <form id ="frmLogin" runat ="server" style="width: 211px; margin-left: 8px" >--%>


    <table style="height: 184px; width: 200px; color: #000000;" >
    
        <tr>
            <td>
                <asp:Label ID ="UserType" runat ="server"  Text = "UserType:"></asp:Label>
            </td>    
            <td style="width: 142px">
                <asp:DropDownList ID ="ddlUserType" runat ="server">
                    <asp:ListItem Selected ="True" Value ="0">Select UserType</asp:ListItem>
                    <asp:ListItem>Admin</asp:ListItem>
                    <asp:ListItem>Company</asp:ListItem>
                    <asp:ListItem>Buyer</asp:ListItem>
                </asp:DropDownList>
                <asp:RequiredFieldValidator ID="rfvUserType" runat="server" ErrorMessage="Please Select Valid UserType"
                 ControlToValidate ="ddlUserType" ValidationGroup ="u1" InitialValue ="0" ForeColor ="Red">*</asp:RequiredFieldValidator>
            </td>
        </tr>

        <tr>
            <td>
                <asp:Label ID ="lblUsername" runat ="server" Text ="EmailId:" ></asp:Label>
            </td>
            <td style="width: 142px">
                <asp:TextBox ID ="txtUsername" runat ="server" ></asp:TextBox>
                <asp:TextBoxWatermarkExtender ID="txtUsername_TextBoxWatermarkExtender" 
                    runat="server" Enabled="True" TargetControlID="txtUsername" WatermarkText ="Enter your EmailId">
                </asp:TextBoxWatermarkExtender>
                <asp:RequiredFieldValidator ID="rfvUsername" runat="server" ErrorMessage="Please Enter EmailId"
                ControlToValidate="txtUsername" ValidationGroup ="u1" ForeColor ="Red">*</asp:RequiredFieldValidator>

                <asp:RegularExpressionValidator ID="revUsername" runat="server" ErrorMessage="Please Enter Valid EmailId"
                ControlToValidate ="txtUsername" ValidationGroup ="u1" ForeColor ="Red"
                    ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*">*</asp:RegularExpressionValidator>
            </td>
        </tr>

        <tr>
            <td>
                <asp:Label ID ="lblPassword" runat ="server" Text ="Password:"></asp:Label>
            </td>
            <td style="width: 142px">
                <asp:TextBox ID ="txtPassword" runat ="server" TextMode ="Password" ></asp:TextBox>
                <asp:TextBoxWatermarkExtender ID="txtPassword_TextBoxWatermarkExtender" 
                    runat="server" Enabled="True" TargetControlID="txtPassword" WatermarkText ="Password">
                </asp:TextBoxWatermarkExtender>
                <asp:RequiredFieldValidator ID="rfvPassword" runat="server" ErrorMessage="Please Enter Password:"
                ControlToValidate ="txtPassword" ValidationGroup ="u1" ForeColor ="Red">*</asp:RequiredFieldValidator>
            </td>
        </tr>

        <tr>
            <td align="center" colspan="2">
                <asp:Button ID ="btnLogin" runat ="server" Text ="Login" 
                    CausesValidation ="true" onclick="btnLogin_Click"  ValidationGroup ="u1" />
            </td>
        </tr>

        <tr>
            <td align="center" colspan="2">
                <asp:ValidationSummary ID="vsLogin" runat="server" ShowMessageBox ="true" ShowSummary ="false" ValidationGroup ="u1" ForeColor ="Red" />
            </td>
        </tr>
        <tr>
         <td align ="center" colspan ="2">
            <asp:Label ID="Label1" runat="server" ForeColor ="Red"></asp:Label></td>
        </tr>
        <tr>
       
            <td align ="center" colspan ="2"><asp:HyperLink ID="btnFP" runat="server" NavigateUrl ="~/ForgotPassword.aspx" Font-Underline="True">Forgot Password?</asp:HyperLink></td>
        </tr>
    </table>
    
<%--</form>--%>
</asp:Content>
<asp:Content ContentPlaceHolderID ="cphAdvertisement" runat ="server" >
    <asp:AdRotator ID="AdRotator1" runat="server" AdvertisementFile="~/Advertisement.xml" />
</asp:Content>